/*Alter a la tabla XX_Vendedores_Sup*/
ALTER TABLE XX_Vendedores_Sup ADD FOREIGN KEY (XX_Supervisores_Comision_ID) REFERENCES XX_Supervisores_Comision(XX_Supervisores_Comision_ID) ON UPDATE CASCADE ON DELETE RESTRICT 

ALTER TABLE XX_Vendedores_Sup ADD FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner(C_BPartner_ID) ON UPDATE CASCADE ON DELETE RESTRICT 

ALTER TABLE XX_Vendedores_Sup ADD FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client(AD_Client_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Vendedores_Sup ADD FOREIGN KEY (AD_Org_ID) REFERENCES AD_Org(AD_Org_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

/*Alter a la tabla XX_Porcentaje_Cat_Sup*/
ALTER TABLE XX_Porcentaje_Cat_Sup ADD FOREIGN KEY (M_Product_Category_ID) REFERENCES M_Product_Category(M_Product_Category_ID) ON UPDATE CASCADE ON DELETE RESTRICT

ALTER TABLE XX_Porcentaje_Cat_Sup ADD FOREIGN KEY (XX_Supervisores_Comision_ID) REFERENCES XX_Supervisores_Comision(XX_Supervisores_Comision_ID) ON UPDATE CASCADE ON DELETE RESTRICT

ALTER TABLE XX_Porcentaje_Cat_Sup ADD FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client(AD_Client_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Porcentaje_Cat_Sup ADD FOREIGN KEY (AD_Org_ID) REFERENCES AD_Org(AD_Org_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

/*Alter a la tabla XX_Retencion*/
ALTER TABLE XX_Retencion ADD FOREIGN KEY (XX_ConceptoRetencion_ID) REFERENCES XX_ConceptoRetencion(XX_ConceptoRetencion_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Retencion ADD FOREIGN KEY (C_Tax_ID) REFERENCES C_Tax(C_Tax_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Retencion ADD FOREIGN KEY (C_Charge_ID) REFERENCES C_Charge(C_Charge_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Retencion ADD FOREIGN KEY (XX_TipoPersona_ID) REFERENCES XX_TipoPersona(XX_TipoPersona_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Retencion ADD FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client(AD_Client_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Retencion ADD FOREIGN KEY (AD_Org_ID) REFERENCES AD_Org(AD_Org_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

/*Alter a la tabla C_DocType*/
ALTER TABLE C_DocType ADD FOREIGN KEY (XX_SerieNroControl_ID) REFERENCES XX_SerieNroControl(XX_SerieNroControl_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE C_DocType ADD FOREIGN KEY (XX_Doc_Reverso_ID) REFERENCES C_DocType(C_DocType_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

/*Alter a la tabla C_Order*/
ALTER TABLE C_Order ADD FOREIGN KEY (XX_Convenio_Cosecha_ID) REFERENCES XX_Convenio_Cosecha(XX_Convenio_Cosecha_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE C_Order ADD FOREIGN KEY (XX_Conductor_ID) REFERENCES XX_Conductor(XX_Conductor_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE C_Order ADD FOREIGN KEY (XX_Vehiculo_ID) REFERENCES XX_Vehiculo(XX_Vehiculo_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

/*Alter a la tabla C_Invoice*/
ALTER TABLE C_Invoice ADD FOREIGN KEY (XX_ConceptoRetencion_ID) REFERENCES XX_ConceptoRetencion(XX_ConceptoRetencion_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE C_Invoice ADD FOREIGN KEY (XX_Convenio_Cosecha_ID) REFERENCES XX_Convenio_Cosecha(XX_Convenio_Cosecha_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE C_Invoice ADD FOREIGN KEY (M_Shipper_ID) REFERENCES M_Shipper(M_Shipper_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE C_Invoice ADD FOREIGN KEY (XX_Conductor_ID) REFERENCES XX_Conductor(XX_Conductor_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE C_Invoice ADD FOREIGN KEY (XX_Vehiculo_ID) REFERENCES XX_Vehiculo(XX_Vehiculo_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE C_Invoice ADD CONSTRAINT C_BP_Bill_Location FOREIGN KEY (bill_location_id) REFERENCES C_BPartner_Location (C_BPartner_Location_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

/*Alter a la tabla XX_Convenio_Cosecha*/
ALTER TABLE XX_Convenio_Cosecha ADD FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner(C_BPartner_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Convenio_Cosecha ADD FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client(AD_Client_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Convenio_Cosecha ADD FOREIGN KEY (AD_Org_ID) REFERENCES AD_Org(AD_Org_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

/*Alter a la tabla XX_Conductor*/
ALTER TABLE XX_Conductor ADD FOREIGN KEY (M_Shipper_ID) REFERENCES M_Shipper(M_Shipper_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Conductor ADD FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client(AD_Client_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Conductor ADD FOREIGN KEY (AD_Org_ID) REFERENCES AD_Org(AD_Org_ID) ON UPDATE CASCADE ON DELETE RESTRICT;


/*Alter a la tabla XX_Vehiculo*/
ALTER TABLE XX_Vehiculo ADD FOREIGN KEY (M_Shipper_ID) REFERENCES M_Shipper(M_Shipper_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Vehiculo ADD FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client(AD_Client_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Vehiculo ADD FOREIGN KEY (AD_Org_ID) REFERENCES AD_Org(AD_Org_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

/*Alter a la tabla M_InOut*/
ALTER TABLE M_InOut ADD FOREIGN KEY (XX_Conductor_ID) REFERENCES XX_Conductor(XX_Conductor_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE M_InOut ADD FOREIGN KEY (XX_Vehiculo_ID) REFERENCES XX_Vehiculo(XX_Vehiculo_ID) ON UPDATE CASCADE ON DELETE RESTRICT;


/*Alter a la tabla C_Charge*/
ALTER TABLE C_Charge ADD FOREIGN KEY (M_Product_Category_ID) REFERENCES M_Product_Category(M_Product_Category_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

/*Alter a la tabla XX_Retencion_IVA*/
ALTER TABLE XX_Retencion_IVA ADD FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client(AD_Client_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Retencion_IVA ADD FOREIGN KEY (AD_Org_ID) REFERENCES AD_Org(AD_Org_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Retencion_IVA ADD FOREIGN KEY (C_Charge_ID) REFERENCES C_Charge(C_Charge_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_Retencion_IVA ADD FOREIGN KEY (C_Tax_ID) REFERENCES C_Tax(C_Tax_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

/*Alter a la Tabla C_BPartner*/
ALTER TABLE C_BPartner ADD FOREIGN KEY (XX_Retencion_IVA_ID) REFERENCES XX_Retencion_IVA(XX_Retencion_IVA_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

/*Alter a la Tabla C_CashLine*/
ALTER TABLE C_CashLine ADD FOREIGN KEY (C_Bank_ID) REFERENCES C_Bank(C_Bank_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE C_CashLine ADD FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner(C_BPartner_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE C_CashLine ADD FOREIGN KEY (C_Activity_ID) REFERENCES C_Activity(C_Activity_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE C_CashLine ADD FOREIGN KEY (C_Tax_ID) REFERENCES C_Tax(C_Tax_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

/*Alter a la Tabla C_Cash*/
ALTER TABLE C_Cash ADD FOREIGN KEY (C_DocType_ID) REFERENCES C_DocType(C_DocType_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE C_Cash ADD FOREIGN KEY (C_DocTypeTarget_ID) REFERENCES C_DocType(C_DocType_ID) ON UPDATE CASCADE ON DELETE RESTRICT;


/*Alter a la Tabla XX_FormatoArchivo*/
ALTER TABLE XX_FormatoArchivo ADD FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client(AD_Client_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_FormatoArchivo ADD FOREIGN KEY (AD_Org_ID) REFERENCES AD_Org(AD_Org_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_FormatoArchivo ADD FOREIGN KEY (AD_Table_ID)REFERENCES AD_Table(AD_Table_ID) ON UPDATE CASCADE ON DELETE RESTRICT;


/*Alter a la Tabla XX_LineaFormatoArchivo*/
ALTER TABLE XX_LineaFormatoArchivo ADD FOREIGN KEY (AD_Client_ID) REFERENCES AD_Client(AD_Client_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_LineaFormatoArchivo ADD FOREIGN KEY (AD_Org_ID) REFERENCES AD_Org(AD_Org_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_LineaFormatoArchivo ADD FOREIGN KEY (XX_FormatoArchivo_ID) REFERENCES XX_FormatoArchivo(XX_FormatoArchivo_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_LineaFormatoArchivo ADD FOREIGN KEY (XX_FormatoHijo_ID) REFERENCES XX_FormatoArchivo(XX_FormatoArchivo_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE XX_LineaFormatoArchivo ADD FOREIGN KEY (AD_Column_ID) REFERENCES AD_Column(AD_Column_ID) ON UPDATE CASCADE ON DELETE RESTRICT;


/*Alter a la Tabla C_BankAccountDoc*/
ALTER TABLE C_BankAccountDoc ADD FOREIGN KEY (AD_Table_ID) REFERENCES AD_Table(AD_Table_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE  ADD FOREIGN KEY () REFERENCES XX() ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE  ADD FOREIGN KEY () REFERENCES XX() ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE  ADD FOREIGN KEY () REFERENCES XX() ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE  ADD FOREIGN KEY () REFERENCES XX() ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE  ADD FOREIGN KEY () REFERENCES XX() ON UPDATE CASCADE ON DELETE RESTRICT;
