SELECT (CASE WHEN ABS((CASE WHEN CURRENT_DATE = NULL THEN CURRENT_DATE ELSE CURRENT_DATE END - FECHA_VENCIMIENTO)) < 150 THEN 'HASTA 150 DIAS'
	WHEN ABS((CASE WHEN CURRENT_DATE = NULL THEN CURRENT_DATE ELSE CURRENT_DATE END - FECHA_VENCIMIENTO)) >= 150 THEN 'MAYORES A 150 DIAS' END) DIAS_VEN,
	   NOMBRE_CONTRAPARTE, C_BPARTNER_ID,
	   NOMBRE_CONVENIO,
	   ORDEN, TO_CHAR(FECHA_ORDEN,'DD/MM/YYYY') FECHA_ORDEN, MONTO_ORDEN,
	   FACTURA, TO_CHAR(FECHA_FACTURA,'DD/MM/YYYY') FECHA_FACTURA, MONTO_FACTURA,
	   DESPACHO, TO_CHAR(FECHA_DESPACHO,'DD/MM/YYYY') FECHA_DESPACHO,
	   TO_CHAR(FECHA_VENCIMIENTO,'DD/MM/YYYY') FECHA_VENCIMIENTO, TOTAL_PAGO,
	   F_P, (C_BPARTNER_ID || FACTURA) CONCAT_CONTRAPARTE, NOMBRE_GRUPO,
	   ABS(ROUND((DECODE(SYSDATE, NULL, SYSDATE, SYSDATE) - FECHA_VENCIMIENTO))) DIAS,
	   ROUND((DECODE(SYSDATE, NULL, SYSDATE, SYSDATE) - FECHA_VENCIMIENTO)) DIAS_MOSTRAR
FROM XX_V_VENCIMIENTOS_DET_O_F_D VENCIDOS
WHERE 	  F_P <> 0
	  /*AND (C_BP_GROUP_ID = $P{C_BP_Group_ID} OR DECODE($P{C_BP_Group_ID}, NULL, 1, $P{C_BP_Group_ID}) = 1)
	  AND (C_BPARTNER_ID = $P{C_BPartner_ID} OR DECODE($P{C_BPartner_ID}, NULL, 1, $P{C_BPartner_ID}) = 1)
	  AND (XX_CONVENIO_COSECHA_ID = $P{XX_Convenio_Cosecha_ID} OR DECODE($P{XX_Convenio_Cosecha_ID}, NULL, 1, $P{XX_Convenio_Cosecha_ID}) = 1)
	  AND AD_CLIENT_ID = '1000000'
	  AND ISPAYSCHEDULEVALID <> 'Y'
	  AND ISSOTRX = $P{Venta}*/
ORDER BY NOMBRE_CONTRAPARTE, NOMBRE_CONVENIO, ORDEN, FACTURA, DESPACHO, FECHA_VENCIMIENTO, TOTAL_PAGO ASC