(SELECT COALESCE(TAXBASEAMT, 0) FROM C_INVOICETAX WHERE C_INVOICE_ID = C_Invoice_Header_vt.C_Invoice_Id  AND TAXAMT = 0)


(SELECT COALESCE(ROUND(SUM(TAXBASEAMT),2), 0) FROM C_INVOICETAX WHERE C_INVOICE_ID = C_Invoice_Header_vt.C_Invoice_Id AND TAXAMT <> 0)

SELECT SUM(TaxBaseAmt) FROM C_InvoiceTax WHERE C_Invoice_ID = 1000027

SELECT SUM(TaxBaseAmt) FROM XX_RV_ImpuestoFactura WHERE C_Invoice_ID = 1000027

SELECT * FROM C_InvoiceTax WHERE C_Invoice_ID = 1000027

UPDATE C_Invoice SET XX_Nrocontrol = '00000001' WHERE C_Invoice_ID = 1000027