CREATE OR REPLACE VIEW XX_Vencimientos_Det_O_F_D AS
SELECT CP.C_BPARTNER_ID,CP.NAME NOMBRE_CONTRAPARTE,ORD.C_ORDER_ID, 
  ORD.DOCUMENTNO ORDEN, ORD.DATEORDERED FECHA_ORDEN,
  ORD.DATEORDERED, ORD.GRANDTOTAL MONTO_ORDEN, FAC.C_INVOICE_ID, 
  FAC.DOCUMENTNO FACTURA, FAC.DATEINVOICED FECHA_FACTURA, FAC.DATEINVOICED, 
  FAC.GRANDTOTAL MONTO_FACTURA,DESP.M_INOUT_ID, DESP.DOCUMENTNO DESPACHO,
  DESP.MOVEMENTDATE FECHA_DESPACHO, DESP.MOVEMENTDATE,CPA.NETDAYS DIAS_LISTA,
  (FAC.DATEINVOICED + CPA.NETDAYS) FECHA_VENCIMIENTO,
  FAC. GRANDTOTAL - CASE WHEN SUM(LPA.AMOUNT + LPA.DISCOUNTAMT) = NULL THEN 0 ELSE SUM(LPA.AMOUNT + LPA.DISCOUNTAMT) END F_P,
  CASE WHEN SUM(LPA.AMOUNT + LPA.DISCOUNTAMT) = NULL THEN 0 ELSE SUM(LPA.AMOUNT + LPA.DISCOUNTAMT) END TOTAL_PAGO, 
  FAC.AD_CLIENT_ID, FAC.AD_ORG_ID, FAC.ISSOTRX, FAC.DOCSTATUS, FAC.ISPAYSCHEDULEVALID, GCP.C_BP_GROUP_ID, GCP.NAME NOMBRE_GRUPO,
  CC.XX_CONVENIO_COSECHA_ID, CC.NOMBRE NOMBRE_CONVENIO, FAC.C_INVOICE_ID AS RECORD_ID,
  FAC.CREATED, FAC.CREATEDBY, FAC.UPDATED, FAC.UPDATEDBY,318 AS AD_TABLE_ID , MAX(APA.DATEACCT) FECHA_UL_PAGO
  FROM   C_INVOICE FAC
    INNER JOIN C_BPARTNER CP ON(CP.C_BPARTNER_ID = FAC.C_BPARTNER_ID)
    INNER JOIN C_BPARTNER_LOCATION LCP ON(FAC.C_BPARTNER_LOCATION_ID = LCP.C_BPARTNER_LOCATION_ID)
    INNER JOIN C_LOCATION LOC ON (LCP.C_LOCATION_ID = LOC.C_LOCATION_ID)
    INNER JOIN C_BP_GROUP GCP ON (GCP.C_BP_GROUP_ID = CP.C_BP_GROUP_ID) 
    INNER JOIN M_PRICELIST LSP ON(LSP.M_PRICELIST_ID = FAC.M_PRICELIST_ID)
    INNER JOIN C_PAYMENTTERM CPA ON(CPA.C_PAYMENTTERM_ID = FAC.C_PAYMENTTERM_ID)
    INNER JOIN C_DOCTYPE DOC ON(DOC.C_DOCTYPE_ID = FAC.C_DOCTYPE_ID)
    LEFT JOIN XX_CONVENIO_COSECHA CC ON(CC.XX_CONVENIO_COSECHA_ID = FAC.XX_CONVENIO_COSECHA_ID)
    LEFT JOIN C_ALLOCATIONLINE LPA ON (LPA.C_INVOICE_ID = FAC.C_INVOICE_ID)
    LEFT JOIN C_ALLOCATIONHDR APA ON (APA.C_ALLOCATIONHDR_ID = LPA.C_ALLOCATIONHDR_ID)
    LEFT JOIN C_ORDER ORD ON(ORD.C_ORDER_ID = FAC.C_ORDER_ID)
    LEFT JOIN M_INOUT DESP ON(DESP.C_ORDER_ID = ORD.C_ORDER_ID)
    WHERE  FAC.XX_C_INVOICE_ID IS NULL 
    AND FAC.DOCSTATUS IN ('CO', 'CL')
    AND ORD.DOCSTATUS IN ('CO', 'CL') OR ORD.DOCSTATUS IS NULL
    AND DESP.DOCSTATUS IN ('CO', 'CL') OR DESP.DOCSTATUS IS NULL
 GROUP BY FAC.DOCUMENTNO,
      CP.C_BPARTNER_ID,
      CP.NAME,
      FAC.C_INVOICE_ID,
      FAC.GRANDTOTAL,
      LSP.NAME,
      FAC.DATEINVOICED,
      CPA.NETDAYS,
      ORD.C_ORDER_ID,
      ORD.DOCUMENTNO,
      ORD.DATEORDERED,
      ORD.GRANDTOTAL,
      FAC.AD_CLIENT_ID,
      FAC.AD_ORG_ID,
      FAC.ISSOTRX,
      FAC.DOCSTATUS,
      FAC.ISPAYSCHEDULEVALID,
      GCP.C_BP_GROUP_ID,
      GCP.NAME,
      DESP.M_INOUT_ID,
      DESP.DOCUMENTNO,
      DESP.MOVEMENTDATE,
      CC.XX_CONVENIO_COSECHA_ID,
      CC.NOMBRE,
   FAC.CREATED,
   FAC.CREATEDBY,
   FAC.UPDATED,
   FAC.UPDATEDBY